const { format_quiz_table, unescapingObj, groupBy, groupByKey, categoriesFixer, switchKey, joinUsersByTopicId, removeSpacesFromStr, gradeValidate, findAnswerID, infoValidate, escapeObject, escapingQuiz } = require('./object_validation.js');

// let list1 = {
//     '1': {
//         answer_correct: { 86: true },
//         answer_prompt: { 86: "USER_INPUT" },
//         answer_soft_delete: { 86: false },
//         base64: null,
//         category: "Tech",
//         display_type_description: "Radio",
//         display_type_id: 1,
//         expected_response: "Troubleshooting↵Research outside of Confluence↵Not concerned with ownership↵Technical knowledge↵Greater focus on scope",
//         image: false,
//         point_value: 5,
//         prompt: "List 3 differences between handling a tech ticket and an account ticket.",
//         question_soft_delete: false,
//         question_type_description: "textfield input",
//         question_type_id: 2,
//         quiz_id: 1,
//         quiz_name: "General Tech",
//         sort: 1,
//         topic: "General Tech",
//         topic_id: 1,
//         training_module: "Placeholder",
//         training_url: "http://localhost:3000/edit/1"
//     },
//     '6': {
//         answer_correct: { 14: false, 16: false, 17: false, 18: true },
//         answer_prompt: { 14: "Playtime tab", 16: "Application Crash section", 17: "History tab", 18: "Content log" },
//         answer_soft_delete: { 14: false, 16: false, 17: false, 18: false },
//         base64: null,
//         category: "Tech",
//         display_type_description: "Radio",
//         display_type_id: 1,
//         expected_response: "false",
//         image: false,
//         point_value: 5,
//         prompt: "Where can you diagnose a Steampipe Error?↵",
//         question_soft_delete: false,
//         question_type_description: "selected input",
//         question_type_id: 1,
//         quiz_id: 1,
//         quiz_name: "General Tech",
//         sort: 1,
//         topic: "General Tech",
//         topic_id: 1,
//         training_module: "",
//         training_url: "",
//     }
// }

// describe('format_quiz_table', function () {
//     let list1 = {
//         '1': {
//             answer_correct: { 86: true },
//             answer_prompt: { 86: "USER_INPUT" },
//             answer_soft_delete: { 86: false },
//             base64: null,
//             category: "Tech",
//             display_type_description: "Radio",
//             display_type_id: 1,
//             expected_response: "Troubleshooting↵Research outside of Confluence↵Not concerned with ownership↵Technical knowledge↵Greater focus on scope",
//             image: false,
//             point_value: 5,
//             prompt: "List 3 differences between handling a tech ticket and an account ticket.",
//             question_soft_delete: false,
//             question_type_description: "textfield input",
//             question_type_id: 2,
//             quiz_id: 1,
//             quiz_name: "General Tech",
//             sort: 1,
//             topic: "General Tech",
//             topic_id: 1,
//             training_module: "Placeholder",
//             training_url: "http://localhost:3000/edit/1"
//         },
//         '6': {
//             answer_correct: { 14: false, 16: false, 17: false, 18: true },
//             answer_prompt: { 14: "Playtime tab", 16: "Application Crash section", 17: "History tab", 18: "Content log" },
//             answer_soft_delete: { 14: false, 16: false, 17: false, 18: false },
//             base64: null,
//             category: "Tech",
//             display_type_description: "Radio",
//             display_type_id: 1,
//             expected_response: "false",
//             image: false,
//             point_value: 5,
//             prompt: "Where can you diagnose a Steampipe Error?↵",
//             question_soft_delete: false,
//             question_type_description: "selected input",
//             question_type_id: 1,
//             quiz_id: 1,
//             quiz_name: "General Tech",
//             sort: 1,
//             topic: "General Tech",
//             topic_id: 1,
//             training_module: "",
//             training_url: "",
//         }
//     }
//     it('should be a function', function () {
//         expect(format_quiz_table(list1)).toBeInstanceOf(Function);
//     });
// });



describe('switchKey', function() {
    let list1 = {
        '1': {
            base64: null,
            display_type_description: "Radio",
            display_type_id: 1,
            expected_response: "",
            image: false,
            point_value: 5,
            prompt: "asdsad",
            question_soft_delete: false,
            question_type_description: "selected input",
            question_type_id: 2,
            quiz_name: "",
            sort: 1,
            topic: "",
            training_module: "",
            training_url: "",
        },
        '2': {
            base64: null,
            display_type_description: "Radio",
            display_type_id: 1,
            expected_response: "",
            image: false,
            point_value: 1,
            prompt: "",
            question_soft_delete: false,
            question_type_description: "radio input",
            question_type_id: 2,
            quiz_name: "",
            sort: 1,
            topic: "",
            training_module: "",
            training_url: "",
        },
        '3': {
            base64: null,
            display_type_description: "Radio",
            display_type_id: 1,
            expected_response: "",
            image: false,
            point_value: 1,
            prompt: "",
            question_soft_delete: false,
            question_type_description: "dropdown input",
            question_type_id: 2,
            quiz_name: "",
            sort: 1,
            topic: "",
            training_module: "",
            training_url: "",
        }
    };
    let list2 = {
        'selected input': {
            base64: null,
            display_type_description: "Radio",
            display_type_id: 1,
            expected_response: "",
            image: false,
            point_value: 5,
            prompt: "asdsad",
            question_soft_delete: false,
            question_type_description: "selected input",
            question_type_id: 2,
            quiz_name: "",
            sort: 1,
            topic: "",
            training_module: "",
            training_url: "",
        },
        'radio input': {
            base64: null,
            display_type_description: "Radio",
            display_type_id: 1,
            expected_response: "",
            image: false,
            point_value: 1,
            prompt: "",
            question_soft_delete: false,
            question_type_description: "radio input",
            question_type_id: 2,
            quiz_name: "",
            sort: 1,
            topic: "",
            training_module: "",
            training_url: "",
        },
        '3': {
            base64: null,
            display_type_description: "Radio",
            display_type_id: 1,
            expected_response: "",
            image: false,
            point_value: 1,
            prompt: "",
            question_soft_delete: false,
            question_type_description: "dropdown input",
            question_type_id: 2,
            quiz_name: "",
            sort: 1,
            topic: "",
            training_module: "",
            training_url: "",
        }
    };
    let list3 = {
        'selected input': {
            base64: null,
            display_type_description: "Radio",
            display_type_id: 1,
            expected_response: "",
            image: false,
            point_value: 5,
            prompt: "asdsad",
            question_soft_delete: false,
            question_type_description: "selected input",
            question_type_id: 2,
            quiz_name: "",
            sort: 1,
            topic: "",
            training_module: "",
            training_url: "",
        },
        'radio input': {
            base64: null,
            display_type_description: "Radio",
            display_type_id: 1,
            expected_response: "",
            image: false,
            point_value: 1,
            prompt: "",
            question_soft_delete: false,
            question_type_description: "radio input",
            question_type_id: 2,
            quiz_name: "",
            sort: 1,
            topic: "",
            training_module: "",
            training_url: "",
        },
        'dropdown input': {
            base64: null,
            display_type_description: "Radio",
            display_type_id: 1,
            expected_response: "",
            image: false,
            point_value: 1,
            prompt: "",
            question_soft_delete: false,
            question_type_description: "dropdown input",
            question_type_id: 2,
            quiz_name: "",
            sort: 1,
            topic: "",
            training_module: "",
            training_url: "",
        }
    };
    it('should be a sorted list or something', function() {
        // expect(switchKey(list1, 'question_type_description')).toEqual(list2)
        expect(switchKey(list1, 'question_type_description')).toEqual(list3)
    });
});